version: '3.7'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
            target: prod
    proxy:
        build: 
            context: .
            dockerfile: Dockerfile
            target: proxy
        ports:
            - "8080:80"