version: '3.7'
services:
    dock-rea-dev-i-prod:
        image: dock-rea-prod-i-img
        container_name: dock-rea-prod-i-cont
        build: 
            context: ../
            dockerfile: .docker/Dockerfile
        ports:
            - "8080:80"