version: '3.7'
services:
    dock-rea-dev-i-srv:
        # Workaround to create-react-app bug: https://github.com/facebook/create-react-app/issues/8688#issuecomment-627325545 
        stdin_open: true 

        # The following lines were commented due to the unknow error on DEV build
        # container_name: dock-rea-dev-i-cont
        # image: dock-rea-dev-i-img
        
        build: 
            context: ../
            dockerfile: .docker/Dockerfile.dev
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - ../:/app:delegated